### ISSUE TITLE
Publish a Docker image?

### ISSUE THREAD

**Issue by AnthonyMastrean** [jandelgado/rabtap#40]
It would be _awesome_ to have rabtap available as a Docker image. I don't know if it's better to run a Go build inside the Dockerfile or just to download/extract the prebuilt binary.

**Comment by jandelgado** [comment]
The go binaries of rabtap are statically linked, so they run on the most linux systems out of the box. What would the benefit of a dockerized version be? What is your use-case?

**Comment by AnthonyMastrean** [comment]
Yeah, it's not strictly necessary and your project is easy to run manually. But, I have an application + RabbitMQ bundled up in a Compose manifest.

```yml
services:
    app:
        image: registry.gitlab.com/example/app:latest
        depends_on:
            - rabbitmq
    rabbit:
        image: rabbitmq:3.8-alpine
```

Now, I may or may not publish the necessary ports (depending on the env... localhost, development, or production). So, it would be nice to have rabtap _inside_ the Compose project (and therefore, the Docker network).

```yml
services:
    app:
        image: registry.gitlab.com/example/app:latest
        depends_on:
            - rabbitmq
    rabbit:
        image: rabbitmq:3.8-alpine
    rabtap:
        image: jandelgado/rabtap:latest
```

I _should_ be able to run rabtap commands without any installation on the host and without any ports published to the host:

```
$ docker-compose exec rabbit rabbitmqctl trace_on
$ docker-compose run rabtap --tap amq.rabbitmq.trace:#
```

---

**Update:** I am also happy to create my own Dockerfile, but I figured I'd drop a note here first :)

**Comment by AndreSteenveld** [comment]
I took a quick stab at this because I have a similar use-case where I want to use rabtap as a piece of instrumentation in my compose stack. The docker file ended up with was:
```
FROM debian:buster-slim as builder

RUN apt-get update \
	&& apt-get install -y git golang-go \
	&& go get -v github.com/jandelgado/rabtap/cmd/rabtap

FROM debian:buster-slim as rabtap
COPY --from=builder /root/go/bin/rabtap /usr/local/bin
```
Building it with (in the same directory as the dockerfile) `docker build -t rabtap .` gives me a image call rabtap I can use in my compose file. Or reference the dockerfile in the compose file and do a build it using that.

**Comment by jmgarnier** [comment]
Thanks @AndreSteenveld !

> I took a quick stab at this because I have a similar use-case where I want to use rabtap as a piece > Building it with (in the same directory as the dockerfile) `docker build -t rabtap .` gives me a image call rabtap I can use in my compose file. Or reference the dockerfile in the compose file and do a build it using that.

Do you mind sharing your `docker-compose.yml` ?

My current WIP:
```yaml
  rabtap:
    image: rabtap
    command: "rabtap tap --uri amqp://guest:guest@localhost:5672/ amq.topic:#"
```

*I will update that comment if I make it work* ;)
